### ISSUE TITLE
Documentation in English

### ISSUE THREAD

**Issue by gamefundas** [Toparvion/analog#13]
I am trying to translate and understand this amazing tool but any time soon the english documentation will become available.

**Comment by gamefundas** [comment]
At this point I am trying to configure the tool to see if logs from a central EFS filesystem can be viewed/tailed from this tool.

**Comment by Toparvion** [comment]
@gamefundas, I appreciate your interest in AnaLog and sorry for so late answer.

Composing of full, thorough documentation is a matter of time. But to accelerate and ease your experience with AnaLog I'm ready to provide description for the function(s) you need right now. 

In adjacent issue #14 I've written some thoughts on using `scanDir` feature which seems suitable for your use case. You can also find an example on using it on [sample configuration page](https://github.com/Toparvion/analog/wiki/Пример-конфигурации) (in Russian so far).

**Comment by gamefundas** [comment]
I have my own message bundle (messages.properties) in english to replace the web page text but it would be nice to have that externalized to the config location similar to other properties.

**Comment by Toparvion** [comment]
@gamefundas Yes, it's time to support UI localization for AnaLog and I'm going to do it as one of the nearest features. It should be done in different issue as this one is about *documentation* (which is also a great field for work). 

You can attach your message bundle here or to a new issue in order to let me check if I translated the words correctly.

**Comment by Toparvion** [comment]
I've created separate issue #22 devoted to English translation of user interfaces only.

**Comment by gamefundas** [comment]
Look forward to it. Closing this one as #22 will address this.
