### ISSUE TITLE
My first experience with 0.10 release

### ISSUE THREAD

**Issue by gamefundas** [Toparvion/analog#14]
Is the new Analog release compiled using Java 9? Couldn't see this in the requirements. 
Was getting an error on my Java 8 JVM -1.8.0_171.

**Comment by gamefundas** [comment]
Switched to Java 9 and got past that but got some warnings on windows which I am ignoring for now.

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (jar:file:/C:/APPS/Dev/cash/cns/exam
ples/analog/deploy/lib/analog.jar!/BOOT-INF/lib/spring-core-5.0.5.RELEASE.jar!/) to method java.lang.ClassLoader.defineC
lass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Can view console.log and this is cool. 

I see that the following line keeps getting printed in the logs. May be something to look at.

2018-06-11 12:26:08.050  INFO 10896 --- [ask-scheduler-3] o.s.i.a.AggregatingMessageHandler        : Expiring MessageGroup with correlationKey[1]

Also when the log entries gets pushed to the UI. The view should scroll to the bottom to show the most recent log. Currently the view seems to stay at the previous position. So it doesn't give the real tail feel. Had to keep manually scrolling to the bottom of the page to view the recent log lines.

scanDir: is the most preferred configuration in my case as the logs are moved by filebeat to a EFS filesystem. So all application are sending their logs to this central file system. There is a certain structure this is currently managed. 

/logs/appname1/module1/filename.log
/logs/appname1/module2/filename.log
/logs/appname2/module5/filename.log

etc...
Is there a way for me to configure this tailer in a way that these are automatically loaded in the dropdown? As I dont intent to make changes to Analog when a new application/module starts sending logs. This will be a nice feature to have.

**Comment by Toparvion** [comment]
@gamefundas, thank you very much for your interest on AnaLog!

> new Analog release compiled using Java 9

Yes. In fact there was an intermediate (non-public) release v0.9 that was aimed especially at upgrading to Java 9. It's my fault that this requirement is not reflected in v0.10 release notes. I've fixed it.

 > but got some warnings on windows

This warning does not depend on Windows or any other OS and is completely relates to Java 9 modular system (project Jigsaw) and its support in various frameworks (Spring in this case). You are absolutely right in ignoring it totally. I believe this and other similar warnings will disappear as the frameworks support Java 9 fully.

> following line keeps getting printed in the logs. May be something to look at.

As you can see these lines are printed on INFO level (not event WARN). The are absolutely correct as they reflect proper AnaLog functioning. 

> Currently the view seems to stay at the previous position

What browser do you use? Does the behavior depend on whether the log console cleared out (with the right-top button) or not? Also please note that auto scrolling should be activated when either the view port is scrolled manually to the bottom or when "Scroll to bottom" button is clicked. The button appears automatically when the slider on scroll bar is not at the bottom position (you can provoke it by slightly scrolling up with the mouse wheel).

> Is there a way for me to configure this tailer in a way that these are automatically loaded in the dropdown? 

The list of logs detected by `scanDir` feature is refreshed every time you load the AnaLog web page. That means that you can see the changes by simply hitting F5 in browser.
But for the time being this feature does not support neither recursive directory scanning nor multiple directory set in the same log choice group. Though it doesn't seem a big feature to add so if you submit an issue for it I'll try to implement it as soon as possible.

**Comment by gamefundas** [comment]
I believe a lot of these have been addressed and few things have changes since the original release. Will close this one for now and check out the new release.

**Comment by Toparvion** [comment]
@gamefundas Thank you for you feedback!
Hope this time your experience with AnaLog will be much better.
