### ISSUE TITLE
Приложение не стартует

### ISSUE THREAD

**Issue by mnatikk** [Toparvion/analog#3]
версия 0.8
java version "1.8.0_65"

`2018-02-15 22:26:13.519  WARN 25258 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'tailingFlowProvider' defined in URL [jar:file:/Users/mnatikk/app/analog-v0.8/analog.jar!/BOOT-INF/classes!/tech/toparvion/analog/remote/agent/TailingFlowProvider.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tailSpecificsProvider' defined in class path resource [tech/toparvion/analog/remote/server/ServerConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [tech.toparvion.analog.service.tail.TailSpecificsProvider]: Factory method 'tailSpecificsProvider' threw exception; nested exception is java.lang.IllegalStateException: No suitable specifics provider found for tail's idf string: tail: illegal option -- -
Please post this message to https://github.com/Toparvion/analog/issues/new in order to support this  tail implementation in future versions of AnaLog.
`

**Comment by Toparvion** [comment]
@mnatikk, благодарю за проявленный интерес!

Судя по этой ошибке, программе не удалось распознать версию утилиты `tail`, установленной на этой машине. Для прояснения нужна следующая информация:
1. На какой ОС была попытка запуска?
2. Каков результат выполнения команды `tail --version` в консоли?
3. Как выглядит вывод `usage` для этой утилиты `tail`? (если такой вывод доступен)

**Comment by mnatikk** [comment]
1. MacOS 10.12.6
2. и 3.:
`mnatikk$ tail --version`
`tail: illegal option -- -`
`usage: tail [-F | -f | -r] [-q] [-b # | -c # | -n #] [file ...]`

**Comment by Toparvion** [comment]
@mnatikk, спасибо!
Добавил поддержку MacOS'ного `tail`. Прошу проверить ее в действии.
Актуальный дистрибутив [можно скачать](https://github.com/Toparvion/analog/raw/%233-MacOS-tail-support/dist/analog-v0.8.1.zip) пока из ветки.

**Comment by mnatikk** [comment]
@Toparvion, cпасибо, приложение запустилось на сборке 0.8.1
