### ISSUE TITLE
v0.8 run.sh содержит виндовые переносы строк

### ISSUE THREAD

**Issue by mnatikk** [Toparvion/analog#4]
на unix-платформе такой скрипт не запуститься. Приходится менять CRLF на LF. Поменяйте, пожалуйста, в сборке.

**Comment by Toparvion** [comment]
@mnatikk, действительно, при сборке дистрибутива под Windows в скрипт запуска были привнесены умолчательные для этой ОС переносы строк. 
Скрипт исправлен; дистрибутив перезалит.
Спасибо за это замечание! 👍
