### ISSUE TITLE
Подсветка уровня DEBUG в некоторых случаях выводится цветом для уровня INFO

### ISSUE THREAD

**Issue by mnatikk** [Toparvion/analog#6]
Проблема с подсветкой на примере лога приложения `console.out`:
```
2018-02-17 23:53:28.608 DEBUG 61348 --- [on(2)-10.0.63.8] o.s.m.s.b.SimpleBrokerMessageHandler : Broadcasting to 1 sessions.
2018-02-17 23:53:29.112 INFO 61348 --- [ask-scheduler-5] o.s.i.a.AggregatingMessageHandler : Expiring MessageGroup with correlationKey[1]
2018-02-17 23:53:29.115 DEBUG 61348 --- [on(2)-10.0.63.8] o.s.m.s.b.SimpleBrokerMessageHandler : Processing MESSAGE destination=/topic//Users/mnatikk/app/analog-v0.8.1/console.out session=null payload={"lines":[{"text":"2018-02-17 23:53:28.604 INFO 61348 --- [ask-scheduler-8] o.s...(truncated)
2018-02-17 23:53:29.116 DEBUG 61348 --- [on(2)-10.0.63.8] o.s.m.s.b.SimpleBrokerMessageHandler : Broadcasting to 1 sessions.
```
по-строчно из лога подсветка следующих цветов:

DEBUG - серый
INFO - зеленый
DEBUG - зеленый (ожидается серый)
DEBUG - серый

![2018-02-17 23 59 22](https://user-images.githubusercontent.com/12691769/36343416-ac23dc08-143e-11e8-83ec-cfba8a9a5dde.png)

**Comment by Toparvion** [comment]
@mnatikk, причиной ложного срабатывания явился вот этот фрагмент строки:
```
23:53:28.604 INFO 61348
```
Приложение ориентируется на простые вхождения имен уровней в анализируемые строки. Такой примитивный алгоритм был выбран специально, чтобы удовлетворить многообразию форматов логов, особенно в системах наподобие Puppet. 

Ошибка же заключается в том, что для поиска вхождений была задействована заведомо недетерминированная функция, из-за которой совпадение было обнаружено не в начале строки (по DEBUG), а почти в конце (по INFO). Ее замена, однако, займет некоторое время. Как будет сделано, сообщу.

**Comment by Toparvion** [comment]
## ℹ️ Результаты профилирования версий детектора
### Детектор уровней логирования на регулярных выражениях
![before](https://user-images.githubusercontent.com/12630412/38778269-5a723d44-40e1-11e8-9a72-55e0e0e85ab2.png)
(среднее время детектирования **3125 мс**)

### Детектор уровней логирования на низкоуровневой логике
![after](https://user-images.githubusercontent.com/12630412/38778268-5a4da9ca-40e1-11e8-8368-948b282e342a.png)
(среднее время детектирования **41 мс**)

По результатам профилирования в качестве рабочей выбрана версия детектора на низкоуровневой логике.

**Comment by Toparvion** [comment]
✔️ Работы по этой задаче завершены.
Детектор уровней был переписан полностью на низкоуровневой логике, так как замеры производительности предыдущей его реализации показали недопустимую утилизацию им процессора (см. комментарий выше).

ℹ️ Для задачи не будет отдельного релиза всего приложения; она войдет в состав релиза, планируемого к выпуску после завершения #10 (возможность скачивать текущий выбранный лог).
