### ISSUE TITLE
Предустановленный лог в application.yaml не соответсвует имени файла лога приложения

### ISSUE THREAD

**Issue by mnatikk** [Toparvion/analog#7]
в application.yaml указан
```
    plainLogs:
      - console.log as "$f - логи АнаЛога :)" (selected by default)
```
а приложение пишет лог в `console.out`

**Comment by Toparvion** [comment]
@mnatikk, спасибо! Действительно, для скрипта старта под *nix имела место опечатка; должно быть `.log`.
Исправлено; дистрибутив [перезалит](https://github.com/Toparvion/analog/raw/%233-MacOS-tail-support/dist/analog-v0.8.1.zip) в ветку.
Прошу проверить.

**Comment by mnatikk** [comment]
Во! Отлично! Теперь прям классно, скачиваешь дистриб и всё сразу работает из коробки.
