### ISSUE TITLE
При использовании restart запускается второй инстанс приложения

### ISSUE THREAD

**Issue by mnatikk** [Toparvion/analog#8]
При использовании `restart` текущий процесс не опускается, считает что не запущен и запускается второй инстанс приложения, при этом стирается файл `analog.pid` и становится невозможен `stop`.

```
MacMnatikk:analog-v0.8.1 mnatikk$ ./run.sh start
Starting analog ...
analog has been started

MacMnatikk:analog-v0.8.1 mnatikk$ ps -fu mnatikk | grep analog
  501 61348     1   0 11:52   ttys000    0:33.19 /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home//bin/java -D_analog -Xmx256m -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -jar analog.jar
  501 61352 61348   0 11:53   ttys000    0:00.00 tail -F -0 /Users/mnatikk/app/analog-v0.8.1/console.out
  501 61354  1099   0 11:53   ttys000    0:00.00 grep analog

MacMnatikk:analog-v0.8.1 mnatikk$ ./run.sh restart
analog is not running
Starting analog ...
analog has been started

MacMnatikk:analog-v0.8.1 mnatikk$ ps -fu mnatikk | grep analog
  501 61348     1   0 11:52   ttys000    1:46.42 /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home//bin/java -D_analog -Xmx256m -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -jar analog.jar
  501 61612     1   0 12:03   ttys000    0:08.94 /Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home//bin/java -D_analog -Xmx256m -XX:MaxMetaspaceSize=256m -XX:+HeapDumpOnOutOfMemoryError -jar analog.jar
  501 61614  1099   0 12:03   ttys000    0:00.00 grep analog

```

**Comment by Toparvion** [comment]
@mnatikk, вероятно, под MacOS не работает команда `cat $PID_FILE`, отвечающая за определение текущего работающего экземпляра. При этом под Linux/Unix - работает. В чем различие и как его побороть - пока не ясно, так как в приведенном листинге отсутствует явное упоминание этой команды. Потребуется поисследовать ее поведение под MacOS, чтобы это выяснить.

**Comment by Toparvion** [comment]
@mnatikk, в рамках #10 были полностью переделаны скрипты старта (под Unix/Linux/macOS и под Windows). Отныне запускаемый ими процесс по умолчанию остается активным на всем протяжении работы программы и завершается лишь вместе с ней (например, по Ctrl+C или сигналу от ОС). Предположительно, этот подход, а так же более изощренные внутренности скриптов, должны решить описанную проблему.   
Скачать новую версию можно на [странице релиза v0.10](https://github.com/Toparvion/analog/releases/tag/v0.10).

**Comment by Toparvion** [comment]
Поскольку обратной связи не поступило в течении длительного периода времени, заявку закрываю. Если проблема всё же проявит себя вновь, заявку можно переоткрыть или завести новую.
