### ISSUE TITLE
Помогите с примером конфигурации добавления лога с удаленного сервера

### ISSUE THREAD

**Issue by mnatikk** [Toparvion/analog#9]
Два вопроса по конфигурационному файлу.
Первый.
В примере конфигурации в разделе wiki приведено подключение лога с удаленной ноды для композитного лога. Подскажите как настроить несколько plain логов с разных удаленных хостов.

Второй.
Для ноды надо указать порт, в примере 7801. Кто должен на нем висеть?

**Comment by Toparvion** [comment]
@mnatikk,
> как настроить несколько plain логов с разных удаленных хостов.

Подключение одинарных (plain) логов с удаленных серверов сейчас не поддерживается. Мотива у такого решения два:
- _(основной)_ для подключения к удаленному узлу на нем должен быть запущен АнаЛог, используемый в роли **агента**. Но поскольку АнаЛог выполняет обе роли одновременно, не должно составить никакого труда подключиться к нему как к **серверу** (т.е. напрямую через HTTP) и запросить любой одинарный лог. Другими словами, в такой конфигурации передача одинарного лога с одного узла на другой выглядит избыточной.
- _(минорный)_ синтаксис задания plain-логов (`<path> [as <alias>] [(selected[ by default])]`) желательно оставить максимально простым и естественным, а указание узла может добавить ему сложности.

Каков предполагаемый сценарий применения удаленных одинарных логов? Быть может, он не был учтён на этапе проектирования и стоит добавить его поддержку в АнаЛог.

**Comment by Toparvion** [comment]
@mnatikk ,
>  7801. Кто должен на нем висеть?

Если речь идет о текущем (не удаленном) узле, т.е. о том, для которого `myself: true`, то этот порт является одновременно портом *прослушивания* и портом *подключения*. Другими словами, висеть на нем будет само же приложение. Дело в том, что АнаЛог на самом деле всегда работает через связку *сервер-агент*, просто в случае с одним узлом обе этих роли выполняет один и тот же экземпляр приложения, и общение между этими ролями происходит через указанный порт.

Если речь об удаленном узле, то этот порт должен быть равен тому, который прописан в настройках АнаЛога на удаленном узле с пометкой `myself: true`.

**Comment by Toparvion** [comment]
@mnatikk, можно ли считать заданные вопросы отвеченными?
Быть может, нужны какие-либо уточнения или помощь?

**Comment by mnatikk** [comment]
Да, вполне. Спасибо!
